name: Deploy suncorn

on:
  push:
    branches:
      - main  # 在 main 分支有新的推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files to be synchronized
      run: ls -l ./  # 列出当前目录下l所有文件

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 在 GitHub secrets 中配置 SSH key
        ARGS: "-avz  --delete  --ignore-times  --exclude-from='.rsync-ignore'  --verbose"
        SOURCE: "./"
        REMOTE_HOST: "47.116.214.40"  # 替换为你的服务器IP
        REMOTE_USER: "root"  # 替换为你的服务器用户名
        TARGET: "/www/wwwroot/suncorn"  # 服务器上的目标路径
