name: Deploy suncorn

on:
  push:
    branches:
      - main  # 在 main 分支有新的推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: false
        ref: main
        # 保留文件的提交时间戳
        persist-credentials: false
        set-safe-directory: true
        restore-time: true # 保留提交的原始时间戳
    - name: Check current time
      run: date

    - name: List files to be synchronized
      run: ls -la ./  # 列出当前目录下l所有文件

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 在 GitHub secrets 中配置 SSH key
        ARGS: "-avz  --delete  --exclude-from='.rsync-ignore'  --verbose"
        SOURCE: "./"
        REMOTE_HOST: "47.116.214.40"  # 替换为你的服务器IP
        REMOTE_USER: "root"  # 替换为你的服务器用户名
        TARGET: "/www/wwwroot/suncorn"  # 服务器上的目标路径
